import {
  GP_HOMEPAGE_SECTION_AFTER_HEADING_CLASS,
  GP_HOMEPAGE_SECTION_HEADING_CLASS,
} from "./homepageTypography";

/**
 * Landing `/home` section subheadings — Open Sans, shared homepage rhythm.
 */
export const GP_LANDING_SECTION_HEADING_CLASS = `${GP_HOMEPAGE_SECTION_HEADING_CLASS} ${GP_HOMEPAGE_SECTION_AFTER_HEADING_CLASS}`;

export {
  GP_FLOWER_WISDOM_SQUARE_IMAGE_CLASS as GP_LANDING_FLOWER_WISDOM_IMAGE_CLASS,
  GP_FLOWER_WISDOM_SQUARE_MEDIA_CLASS as GP_LANDING_FLOWER_WISDOM_MEDIA_CLASS,
  GP_FLOWER_WISDOM_SQUARE_SKELETON_CLASS as GP_LANDING_FLOWER_WISDOM_SKELETON_CLASS,
} from "./flowerWisdomLayout";
