const APPROVED_GLOBAL_TOAST_MESSAGES = new Set(
  [
    "Address updated successfully",
    "Address added successfully",
    "Address deleted successfully.",
    "Address deleted",
    "Delivery location updated",
    "Delivery address updated",
    "Added to basket",
    "Money added to wallet",
    "Subscription resumed",
    "Subscription updated",
    "Account deleted successfully",
    "Message sent successfully",
    "Copied!",
    "Location permission denied. You can still enter address manually.",
    "Location permission denied. You can enter address manually.",
    "Failed to get location",
    "Failed to switch address",
    "Turn on location permission to use current location.",
    "Could not use current location",
    "Failed to set default",
    "Failed to delete address",
    "Failed to save details. Please try again.",
    "Choose your store or delivery area before adding items to the basket.",
    "Failed to add to basket. Please try again.",
    "Could not save message.",
    "Could not update basket.",
    "Could not update quantity.",
    "Could not update item. Pull to refresh and try again.",
    "Failed to remove item. Please try again.",
    "Could not update message.",
    "Failed to update message. Please try again.",
    "You're offline. Reconnect to continue checkout.",
    "Authentication required. Please login to continue.",
    "Your current location is not saved. Choose a saved address or save this address then try again.",
    "Your wallet balance is low. Please recharge your wallet before starting this subscription.",
    'Use "Switch store" below for this delivery address or choose another address.',
    "Sorry for the inconvenience - this store is currently offline.",
    "Could not verify the store for this delivery address.",
    "Could not switch store for this address.",
    "Payment could not be completed. Please try again.",
    "Payment could not be completed. You were not charged. Please try again.",
    "We could not confirm your payment. If money was debited check My Orders or your bank; refunds usually arrive within a few days.",
    "Could not resume",
    "Failed to switch store",
    "Could not update your basket for this store.",
    "This store is outside the delivery range for your address. Update your address or choose a closer store.",
    "Allow access to your photos to change your profile picture.",
    "Allow camera access to take a profile picture.",
    "Each image must be under 5MB",
    "Allow photo access in Settings to attach an image to your message.",
    "Failed to send message. Please try again.",
    "Cannot open invoice link.",
    "Too many requests. Please wait a moment and try again.",
    "Service temporarily unavailable. Please try again shortly.",
    "Network issue or timeout. Check your connection and try again.",
    "Press again to exit",
  ].map((m) => m.trim().toLowerCase()),
);

export function isApprovedGlobalToastMessage(message: string): boolean {
  const normalized = String(message ?? "").trim().toLowerCase();
  if (!normalized) return false;
  return APPROVED_GLOBAL_TOAST_MESSAGES.has(normalized);
}
